Task 1. Setting up the enviroment
achains/formal-lang-course pull request #1
Opened 2021-09-03 13:33 UTC by achains

Created run_tests.yml and some utility functions in project/graph_utils.py

2021-09-06 13:10 UTC, vdshk requested changes
Также есть пара глобальных замечаний.
* > - [ ] Реализовать консольное приложение, предоставляющее перечисленные ниже возможности. Для работы с графами использовать [cfpq-data](https://jetbrains-research.github.io/CFPQ_Data/tutorial.html#graphs). Данное приложение в дальнейшем будет расширяться. 

    Именно **консольное приложение**. Соответственно должен быть `REPL`. С командами аля `get_graph_info`, `create_two_cycles_graph`, `save_to_dot`, `quit` и т.п. Запускаться `REPL` должен через `python -m project`. 
* >   - [ ] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах.

    Именно **по имени**. В наборе данных у графов есть имена. Такие как `geospecies`, `pizza`, `enzyme`. См. [Get a real graph](https://jetbrains-research.github.io/CFPQ_Data/tutorial.html#get-a-real-graph)
        
* Копируйте из `tasks` полностью описание задачи в комментарий вашего PR и проставляйте чекбоксики, пожалуйста. Так будет и вам и мне проще видеть, что требовалось сделать и что уже сделано.

* Не забудьте написать в `project/README.md` как запускать ваше **консольное приложение**.

* Убедитесь, что ваши тесты покрывают все возможные крайние случаи.
    
> Мой комментарий на русском языке, так как курс читается на русском языке.
Если вы согласны перейти на английский, напишите мне об этом, пожалуйста, в комментариях.

2021-09-06 13:10 UTC, vivalerievich commented on .github/workflows/run_tests.yml
> +name: Check code style
У Вас имена action'ов одинаковые. Это вызывает неоднозначность.
```suggestion
name: Check tests
```

2021-09-06 13:10 UTC, vivalerievich commented on .github/workflows/run_tests.yml
> +        python-version: [ 3.8 ]
Добавьте в матрицу `ubuntu-latest`, `macos-latest`, `windows-latest`, чтобы тестировать ваше решение на всех платформах. Мы в задачах будем использовать только кросс-платформенные библиотеки, поэтому проблем не будет.

2021-09-06 13:10 UTC, vivalerievich commented on project/graph_utils.py
> +import networkx
Импортировать `networkx` лучше следующим образом
```suggestion
import networkx as nx
```

2021-09-06 13:10 UTC, vivalerievich commented on project/graph_utils.py
> +GraphInfo = namedtuple("GraphInfo", ["vertices", "edges", "labels"])
Стандартно используется `nodes`, а не `vertices`
```suggestion
GraphInfo = namedtuple("GraphInfo", ["nodes", "edges", "labels"])
```

2021-09-06 13:10 UTC, vivalerievich commented on project/graph_utils.py
> +def get_graph_info(graph) -> GraphInfo:
Если используете `type hints`, то старайтесь делать это везде.
В основном вы будете работать с `nx.MultiDiGraph`. Но можете также прописать `Union` всех типов графов из `networkx`.
```suggestion
def get_graph_info(graph: nx.MultiDiGraph) -> GraphInfo:
```

2021-09-06 13:10 UTC, vivalerievich commented on project/graph_utils.py
> +        graph.number_of_nodes(), graph.number_of_edges(), cfpq_data.get_labels(graph)
Думаю здесь не стоит включать `verbose` (по умолчанию он включен).
```suggestion
        graph.number_of_nodes(), graph.number_of_edges(), cfpq_data.get_labels(graph, verbose=False)
```

2021-09-06 13:10 UTC, vivalerievich commented on requirements.txt
> +networkx~=2.6.2
`networkx` уже есть в зависимостях у `cfpq_data`. Почему вы его добавили?
```suggestion
```

2021-09-06 13:10 UTC, vivalerievich commented on res/test_graph_utils_2.dot
> +digraph  {
Непонятно для чего используется этот файл. Да и папка `res` в целом.
Если вы хотите написать тест, проверяющий, что вы правильно сохраняете файл в формате DOT, тот этот файл должен быть в папке `tests`. Желательно в `tests/data`.

2021-09-06 13:10 UTC, vivalerievich commented on project/graph_utils.py
> +import networkx
Старайтесь разделять друг от друга импорты `from` и `import`
```suggestion
from collections import namedtuple
from typing import Tuple

import cfpq_data
import networkx
```

2021-09-06 13:10 UTC, vivalerievich commented on project/graph_utils.py
> +def generate_and_save_two_cycle(
Вместо `filename` лучше использовать полный путь к нужному файлу. Посмотрите на [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html?highlight=path#module-pathlib)

2021-09-06 13:10 UTC, vivalerievich commented on tests/test_basic.py
> -import pytest
Файл `test_basic` был в качестве наглядного примера. Далее его стоит удалить

2021-09-06 13:10 UTC, vivalerievich commented on tests/test_basic.py
> +    from project import graph_utils
Все импорты должны быть в начале файла. PEP8, imports

2021-09-06 13:10 UTC, vivalerievich commented on tests/test_basic.py
> +    g = cfpq_data.labeled_binomial_graph(10, 0.5, verbose=False)
Если вы не устанавливаете `seed`, то можете получать разные графы и тест становится недетерминированным.

2021-09-06 13:10 UTC, vivalerievich commented on tests/test_basic.py
> +    assert cfpq_data.get_labels(g) == g_info.labels
1. В unit тестах лучше придерживаться правила один `assert` на тест.
2. Ваш тест неправильно построен. Должен быть виксированный `g_info_expected` например. А так получается, что вы сравниваете одно и то же.
3. Порядок сравнения должен быть `assert actual == expected`

2021-09-06 13:10 UTC, vivalerievich commented on tests/test_basic.py
> +    )
Что этот тест проверяет?
Как минимум стоит проверять то, что тот граф, который вы сохраняете, совпадает с тем, что вы ожидаете увидеть как он сохранится. По сути должен быть `graph_expected.dot` в `tests/data`.

2021-09-06 13:10 UTC, vivalerievich commented on project/graph_utils.py
> +    graph.write_raw(filename)
Также стоит возвращать из функции полный путь до файла
```suggestion
    graph.write_raw(filename)
    return Path(path_to_file).resolve()
```

2021-09-06 13:10 UTC, vivalerievich commented on project/graph_utils.py
> +    """Generates two cycle graph and saves it to <filename> in DOT format"""
> - [ ] По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://jetbrains-research.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph) и сохранять его в указанный файл в формате DOT (использовать pydot).

На самом деле здесь две задачи:
1. По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://jetbrains-research.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph)
2. Cохранять граф в указанный файл в формате DOT (использовать pydot).

Соответственно должно быть две функции, а не одна. Не забудьте, что эти для этих функций тоже нужны тесты.

2021-09-06 13:10 UTC, vivalerievich commented on project/graph_utils.py
> +    num_first: int, num_second: int, edge_labels: Tuple[str, str], filename: str
Имена параметров весьма неоднозначны. Сделайте однозначными. Например так.
```suggestion
    first_cycle_nodes_num: int, second_cycle_nodes_num: int, edge_labels: Tuple[str, str], filename: str
```

2021-09-06 13:10 UTC, vivalerievich commented on project/graph_utils.py
> +    """Returns namedtuple consisted of number of vertices, edges and labels of given graph"""
Используйте [`NumPy docstrings`](https://numpydoc.readthedocs.io/en/latest/format.html).
Минимально требуется: `1. Short summary`, `4. Parameters`, `5. Returns` или `6. Yields`

2021-09-06 13:10 UTC, vivalerievich commented on project/graph_utils.py
> +    """Returns namedtuple consisted of number of vertices, edges and labels of given graph"""
Так должны быть задокументированы все функции и классы

2021-09-13 08:13 UTC, vdshk approved these changes
Молодец :+1:

> Советую, чтобы не сохранять все исправления в истории, сделать `Squash and merge`

2021-09-13 08:20 UTC, merged