Task 2. Regex to DFA
achains/formal-lang-course pull request #2
Opened 2021-09-12 16:25 UTC by achains

## Задача

- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения минимального ДКА по заданному регулярному выражению. [Формат регулярного выражения.](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression).
- [x] Добавить необходимые тесты.

2021-09-13 09:21 UTC, vdshk requested changes
Глобально всё хорошо :+1:
Но есть пара небольших замечаний, которые стоит поправить ;)

> Думаю стоит сначала закрыть первую задачу, потом смерджить ее в `main` и в эту ветку с `main`'а. Чтобы лишних файлов в ПР не было

2021-09-13 09:21 UTC, vdshk commented on tests/test_regex_to_dfa.py
> +    ]
Посмотрите, пожалуйста, на [`@pytest.mark.parametrize`](https://docs.pytest.org/en/6.2.x/parametrize.html) и добавьте больше регулярных выражений (с крайними случаями, например `regex = ""`)

2021-09-13 09:21 UTC, vdshk commented on tests/test_regex_to_dfa.py
> +    assert all(dfa.accepts(word) for word in test_cases)
Также стоит добавить тесты :
* на минимальность построенного ДКА
* на проверку того, что тот ДКА, который вы получаете из функции совпадает с ДКА, который вы ожидаете получить
* на проверку того, что если регулярное выражение неправильное, то вы выдадите нужный `Exception`

2021-09-13 10:46 UTC, achains commented on tests/test_regex_to_dfa.py
> +    assert all(dfa.accepts(word) for word in test_cases)
Done

2021-09-13 13:17 UTC, achains commented on tests/test_regex_to_dfa.py
> +    ]
Сделано!

2021-09-14 07:06 UTC, vdshk approved these changes
Зачтено :+1:

2021-09-14 07:22 UTC, merged