Task 3
achains/formal-lang-course pull request #3
Opened 2021-09-17 06:40 UTC by achains

## Задача

- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения недетерминированного конечного автомата по [графу](https://networkx.org/documentation/stable/reference/classes/multidigraph.html), в том числе по любому из графов, которые можно получить, пользуясь функциональностью, реализованной в [Задаче 1](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task1.md) (загруженный из датасета по имени граф, сгенерированный синтетический граф). Предусмотреть возможность указывать стартовые и финальные вершины. Если они не указаны, то считать все вершины стартовыми и финальными.
- [x] Добавить необходимые тесты.

### Комментарий
Непосредственный пример передачи графов из [Задачи 1](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task1.md) будет представлен в project/repl.py после задачи на объединение реализованных функций с интерфейсом консольного приложения

2021-09-20 11:08 UTC, vdshk requested changes
В целом всё хорошо :+1: 
Только добавьте, пожалуйста, больше разных графов (граф без вершин, граф на 1 вершине, граф без ребер, т.п.) :eyes: 
---
- [ ] Также стоит проверять стартовые и конечные вершины на валидность

2021-09-20 11:08 UTC, vdshk commented on project/utils/automata_utils.py
> +    """
Нехватает секции `Raises`

2021-09-20 13:20 UTC, achains commented on project/utils/automata_utils.py
> +    """
Дописал

2021-09-20 15:18 UTC, achains commented
Добавил больше тестов и проверку вершин в самой функции.

2021-09-21 07:05 UTC, vdshk approved these changes
В целом всё ОК, зачтено :+1: 
Будет совсем хорошо, если еще и мелкое замечание исправите

2021-09-21 07:05 UTC, vdshk commented on project/utils/automata_utils.py
>          raise AutomataException(f"Invalid regular expression")
Если вы трансформируете `Exception`, то стоит делать это через `Exception Chaining` (см. [тут](https://docs.python.org/3/tutorial/errors.html#exception-chaining))
```suggestion
    except MisformedRegexError as exc:
        raise AutomataException(f"Invalid regular expression") from exc
```

2021-09-21 18:08 UTC, merged