Task 4. RPQ
achains/formal-lang-course pull request #4
Opened 2021-09-28 14:10 UTC by achains

# Задача 4. Регулярные запросы

* **Мягкий дедлайн**: 26.09.2021, 23:59
* **Жёсткий дедлайн**: 29.09.2021, 23:59
* Полный балл: 5

## Задача

- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать алгоритм пересечения двух конечных автоматов через тензорное произведение.
- [x] На основе реализованного алгоритма реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе.
  - Для конструирования регулярного запроса использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
  - Для преобразования графа использовать результаты [Задачи 3](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task3.md).
- [x] Добавить необходимые тесты.

2021-10-04 11:28 UTC, vdshk requested changes
В целом всё супер :+1: 

Непонятно почему вы в `test_rpq` используете всего 1 граф. Это не очень хорошо. И довольно важно проверять различные сценарии запроса `rpq`. Как например `rpq` с пустым графом и другие крайние случаи. 

Поскольку есть существенное замечание и `review` запрошено после мягкого дедлайна, то максимум будет `1/2` баллов за задачу :disappointed:

2021-10-04 11:28 UTC, vdshk commented on project/utils/matrix_utils.py
> +            for s_snd, s_snd_idx in other.indexed_states.items():
Постарайтесь подобрать более понятные имена. Лучшее длинне, но понятнее.
И так везде посмотрите, где сходу непонятно

2021-10-04 11:28 UTC, vdshk commented on tests/test_rpq.py
> +    actual_rpq = rpq.rpq(graph, regex_str, start_nodes, final_nodes)
А почему вы всего один граф в тесте используете? Попробуйте подумать о разных крайних случаях

2021-10-04 22:12 UTC, achains commented on tests/test_rpq.py
> +    actual_rpq = rpq.rpq(graph, regex_str, start_nodes, final_nodes)
Добавил больше тестов

2021-10-04 22:13 UTC, achains commented on project/utils/matrix_utils.py
> +            for s_snd, s_snd_idx in other.indexed_states.items():
Это поменял. В других местах, кажется, говорящие названия

2021-10-05 06:54 UTC, vdshk approved these changes
Зачтено :+1:

2021-10-05 09:35 UTC, merged