Task 5. Experiments. RPQ
achains/formal-lang-course pull request #5
Opened 2021-10-06 18:37 UTC by achains

## Задача 5. Экспериментальное исследование алгоритмов для регулярных запросов
[Ссылка на описание задачи](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task5.md)
[Ссылка на Google Colab](https://colab.research.google.com/drive/18JAnDswOkz-QpQAFuHz-aERRqVrdVj_c?authuser=1#scrollTo=gEsQSDtfxVjx)

### Описание задач
- [x] Используя [pyCuBool](https://pypi.org/project/pycubool/) реализовать алгоритм пересечения двух конечных автоматов через тензорное произведение. Аналогично тому, как это было сделано в предыдущей домашней работе. Лучше сразу предусмотреть общий интерфейс функций, чтобы было проще ставить эксперименты.
- [x] Подключить решение из предыдущей работы.
- [x] Сформировать набор данных.
  - [x] Выбрать все графы из раздела [RDF](https://jetbrains-research.github.io/CFPQ_Data/dataset/RDF.html).
  - [x] Используя функцию из первой домашней работы узнать метки рёбер графов и на основе этой информации сформулировать не менее 4 различных запросов к каждому графу. Требования к запросам:
      - Запросы ко всем графам должны следовать некоторому общему шаблону. Например, если есть графы ```g1``` и ```g2``` с различными наборами меток, то ожидается, что запросы к ним будут выглядеть, например, так:
        - ```g1```:
          - ```(l1 | l2)* l3```
          - ```(l3 | l4)+ l1*```
          - ```l1 l2 l3 (l4|l1)*```
        - ```g2```:
          - ```(m1 | m3)* m2```
          - ```(m1 | m3)+ m2*```
          - ```m1 m2 m3 (m3|m1)*```
      - В запросах должны использоваться все общепринятые конструкции регулярных выражений  (замыкание, конкатенация, альтернатива). То есть хотя бы в одном запросе к каждому графу должна быть каждая из этих конструкций.
- [x] С использованием сформированного набора данный провести сравнение производительности алгоритма, основанного на тензорном произведении, реализованного с использованием двух библиотек
  - sciPy (предыдущая работа)
  - pyCuBool (первый пункт этой работы)
- [x] Оформить результаты экспериментов
- [x] Провести анализ результатов
- [x] Сделать notebook доступным по ссылке

2021-10-06 18:48 UTC, achains commented
По личным ощущениям ноутбук на данном этапе кажется сыроватым. Хотелось бы получить Ваши комментарии.

И есть вопрос по следующему моменту: В ноутбуке мне понадобился отличный интерфейс rpq функции от того, [что реализован у меня](https://github.com/achains/formal-lang-course/blob/main/project/utils/rpq.py). А именно, передача query как объект типа Regex, а не как строку. Стоит ли изменить интерфейс в проекте? Или пусть "отличная" функция останется только в ноутбуке.

2021-10-11 08:44 UTC, vdshk requested changes
Здравствуйте!

> Лучше сразу предусмотреть общий интерфейс функций, чтобы было проще ставить эксперименты.

Соответственно лучше, если интерфейс в вашем проекте будет достаточно общим для постановки экспериментов.

* Не увидел в комментарии к пуллреквесту выполненные задачи из задания. Исправьте, пожалуйста.

* Предоставьте, пожалуйста, доступ на комментирование к вашей юпитер-тетрадке (так удобнее будет оставлять комментарии). Если не получится, то напишите об этом, пожалуйста, -- оставлю необходимые комментарии в комментариях к пуллреквесту.

2021-10-11 08:51 UTC, achains commented
Хорошо, тогда интерфейс поправлю после первого ревью. 
Добавил задачи в описание PR
Предоставил доступ на комментирование по Вашей почте из профиля

2021-10-13 20:15 UTC, achains commented
Здравствуйте! В шапке изменена ссылка. В README тоже.
На прошлом аккаунте колаб ограничил использование GPU :)

2021-10-19 07:07 UTC, vadyushkins approved these changes
Есть незначительные замечания в самом ноутбуке.
В общем и целом, -- зачтено :+1:

2021-10-19 18:45 UTC, merged