Task 6. CFG to WNCF
achains/formal-lang-course pull request #6
Opened 2021-10-17 20:18 UTC by achains

# Задача 6. Преобразование грамматики в ОНФХ

* **Мягкий дедлайн**: 17.10.2021, 23:59
* **Жёсткий дедлайн**: 20.10.2021, 23:59
* Полный балл: 2

## Задача

- [x] Используя [возможности pyformlang для работы с контекстно-свободными грамматиками](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html) реализовать **функцию** преобразования контекстно-свободной грамматики в ослабленную нормальную форму Хомского.
- [x] Предусмотреть возможность чтения грамматики из файла. Формат файла определяется возможностями pyformalng. Например, можно использовать [эту функцию](https://pyformlang.readthedocs.io/en/latest/modules/context_free_grammar.html#pyformlang.cfg.CFG.from_text).
- [x] Добавить необходимые тесты.

2021-10-19 09:00 UTC, vadyushkins requested changes
К сожалению в `pyformlang` строится не совсем ОНФХ, так как там удаляются `epsilon` в телах продукций. Однако на занятии проговаривалось, что в ОНФХ `epsilon` **остаются**.

2021-10-19 09:00 UTC, vivalerievich commented on project/utils/CFG_utils.py
> +    return cfg.to_normal_form()
Это не ОНФХ. В ОНФХ в теле продукции может встречаться `epsilon`. Если посмотреть реализацию в `pyformlang`, то там в теле продукции не остается `epsilon`.

2021-10-19 09:00 UTC, vivalerievich commented on tests/data/test_cfg_corrupted.txt
> +6 flatbreads
:+1:

2021-10-19 09:00 UTC, vdshk commented on tests/test_cfg_to_wncf.py
> +def test_cfg_to_wncf_is_normal(default_cfg):
Это похвально, что вы проверяете совпадение полученной ОНФХ с ожидаемой. Однако в `transform_cfg_to_wcnf` вы получаете не ОНФХ. 
Стоит добавить больше тестов. В том числе такой, чтобы можно было понять, что получается именно ОНФХ (в ОНФХ `epsilon`'ы остаются в телах продукций)

2021-10-20 16:14 UTC, achains commented on tests/test_cfg_to_wncf.py
> +def test_cfg_to_wncf_is_normal(default_cfg):
Добавил соответствующую функцию в тесты

2021-10-20 16:14 UTC, achains commented on project/utils/CFG_utils.py
> +    return cfg.to_normal_form()
Исправил

2021-10-25 16:26 UTC, vadyushkins approved these changes
Зачтено

2021-10-26 19:11 UTC, merged