Task 8. CYK
achains/formal-lang-course pull request #8
Opened 2021-11-03 15:19 UTC by achains

# Задача 8. Алгоритм CYK

* **Мягкий дедлайн**: 31.10.2021, 23:59
* **Жёсткий дедлайн**: 03.11.2021, 23:59
* Полный балл: 5

## Алгоритм CYK

Алгоритм CYK является частным случаем алгоритма Хеллингса: CYK решает задачу проверки выводимости для строки методом динамического программирования.

В данной задаче необходимо реализовать именно CYK, а не реализовать алгоритм Хеллингса и запустить его на линейном входе (строке).

## Задача

- [x] Реализовать **функцию**, основанную на алгоритме CYK и проверяющую выводимость заданной строки в заданной КС грамматике.
  - Обратите внимание, что CYK в классическом варианте работает с грамматикой именно в НФХ (не ОНФХ). Так что если для преобразования в НФХ используется pyformlang, то нужно быть аккуратными с пустыми цепочками.
  - Предусмотрите возможность получать грамматику из различных источников (из файла, как результат работы других функций).
  - Предусмотрите возможность получать строку из различных источников (из файла, из консоли, из других функций).
- [x] Добавить необходимые тесты.

2021-11-04 13:25 UTC, vdshk requested changes
Есть одно замечание по поводу реализации `CYK`. Если Вы убедите меня в том, что так, как у Вас написано, тоже верно работает (требуется формальное доказательство того, что Ваша реализация CYK идентична канонической), то получите полный балл. Иначе, только половину полного балла.

2021-11-04 13:25 UTC, vdshk commented on project/grammars/cyk.py
> +    m = [[set() for _ in range(word_len)]] * word_len
```python
>>> d = [[set() for _ in range(2)]] * 2
>>> d
[[set(), set()], [set(), set()]]
>>> d[0][0].add(1)
>>> d
[[{1}, set()], [{1}, set()]]
```
Я думаю, вы такого не ожидали.

Лучше сделать так.
```suggestion
    m = [[set() for _ in range(word_len)] for _ in range(word_len)]
```

Тогда будет
```python
>>> d = [[set() for _ in range(2)] for _ in range(2)] 
>>> d
[[set(), set()], [set(), set()]]
>>> d[0][0].add(1)
>>> d
[[{1}, set()], [set(), set()]]
```

2021-11-07 15:00 UTC, achains commented on project/grammars/cyk.py
> +    m = [[set() for _ in range(word_len)]] * word_len
Это действительно сильно влияет на корректность работы алгоритма. Исправлено.

2021-11-08 12:00 UTC, vdshk approved these changes
Зачтено

2021-11-08 12:36 UTC, merged